repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@^3.0.0
        files: \.(js|jsx|ts|tsx|json|css|md)$

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.10.0"
    hooks:
      - id: biome-format
        additional_dependencies: ["@biomejs/biome@^2.2.5"]
        files: \.(js|jsx|ts|tsx|json)$

  - repo: local
    hooks:
      - id: tsc
        name: TypeScript type check
        entry: npx tsc --noEmit
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

      - id: tests
        name: Run tests
        entry: npm test
        language: system
        pass_filenames: false

      - id: bundle-validation
        name: Bundle validation
        entry: node scripts/check-imports.js
        language: system
        pass_filenames: false
